Reduce stack usage
This patch fixes the following build error:

private/google-modules/wlan/bcm4398/wl_cfgvif.c:3938:1: error: stack frame size (2096) exceeds limit (2048) in 'wl_apply_ap_mlo_config' [-Werror,-Wframe-larger-than]
wl_apply_ap_mlo_config(struct bcm_cfg80211 *cfg,
^
1 error generated.

Fixes: a0cc547df917 ("DHD: Cherry-pick from branch android13-gs-pixel-5.10")
Change-Id: Iac4ca8f6d12ed7c6b013d801ab0caeea04db2bc2
Signed-off-by: Bart Van Assche <bvanassche@google.com>